
---
# This automation simulates the use of the IKEA RODRET Remote control
# connected through Zigbee2MQTT.

# | Button   | Action              |
# | -------- | ------------------- |
# | Up       | Switch on           |
# | Down     | Switch off          |

blueprint:
  source_url: https://raw.githubusercontent.com/NuklearStriker/Home_Assistant/main/blueprints/automation/Z2M_ikea_rodret_switch.yaml

  name: Z2M - IKEA RODRET - Switch

  description: >-
    This automation simulates the use of the IKEA RODRET remote control
    connected through Z2M to control remote switch.

  domain: automation

  input:
    remote:
      name: IKEA RODRET remote control
      description: Select the remote control you wish to use.
      selector:
        entity:
          filter:
            domain: sensor

    target_switch:
      name: Switch
      description: Select the switch entity you wish to control.
      selector:
        entity:
          domain: switch

trigger:
  - platform: state
    entity_id: !input 'remote'
    attribute: action

condition: []

action:
  - variables:
      command: " {{ trigger.to_state.attributes.action }} "
      var_switch: !input target_switch
      
  - choose:
      # Press on UP
      - conditions:
          - condition: template
            value_template: "{{ command == \"on\" }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input target_switch
            data: {}
                        
      # Press on DOWN
      - conditions:
          - condition: template
            value_template: "{{ command == \"off\" }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input target_switch
            data: {}
mode: single
