---
# This automation simulates the use of the IKEA TRADFRI Remote control
# connected through Zigbee2MQTT.
# Inspired by : source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_styrbar_color.yaml

blueprint:
  source_url: https://github.com/NuklearStriker/Home_Assistant/blob/main/blueprints/automation/Z2M_test.yaml

  name: Z2M - IKEA STYRBAR - Color Lights

  description: >-
    This automation simulates the use of the IKEA STYRBAR remote control
    connected through Z2M.

  domain: automation

  input:
    remote:
      name: IKEA STYRBAR remote control
      description: Select the remote control you wish to use.
      selector:
        entity:
          filter:
            - integration: mqtt
              domain: sensor

    target_light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        device:
          entity:
            domain: light

mode: restart
max_exceeded: silent

variables:
  var_light: !input target_light

trigger:
  - platform: state
    entity_id: !input 'remote'
    attribute: action
    
condition: []
    
action:
  - variables:
      command: '{{ trigger.to_state.state }}'
  - choose:
      # Short-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: '{{ command == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness: 120
              rgb_color: [255, 0, 0]

      # Short-Press on the dim-down button.
      - conditions:
          - condition: template
            value_template: '{{ command == "off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light

    # Any other event will cancel the repeat loops.
    default: []
