---
# This automation simulates the use of the IKEA TRADFRI Remote control
# connected through Zigbee2MQTT.

blueprint:
  source_url: https://github.com/NuklearStriker/Home_Assistant/blob/main/blueprints/automation/Z2M_test.yaml

  name: Z2M - IKEA TRADFRI - Color Lights

  description: >-
    This automation simulates the use of the IKEA TRADFRI remote control
    connected through Z2M.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        entity:
          filter:
            domain: sensor

    target_light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

variables:
  var_light: !input target_light

trigger:
  - platform: state
    entity_id: !input 'remote'
    attribute: action
    
condition: []
    
action:
  - variables:
      command: " {{ trigger.to_state.attributes.action }} "
  - choose:
      # Short-Press on the dim-up button.
      - conditions: '{{ command == "toggle" }}'
        sequence:
          - service: light.toggle
            target:
              entity_id: !input target_light
