
---
# This automation simulates the use of the IKEA RODRET Remote control
# connected through Zigbee2MQTT.

# | Button   | Action              |
# | -------- | ------------------- |
# | Up       | Switch on           |
# | Down     | Switch off          |

blueprint:
  source_url: https://raw.githubusercontent.com/NuklearStriker/Home_Assistant/main/blueprints/automation/Z2M_ikea_rodret.yaml

  name: Z2M - IKEA RODRET

  description: >-
    This automation simulates the use of the IKEA RODRET remote control
    connected through Z2M.

  domain: automation

  input:
    remote:
      name: IKEA RODRET remote control
      description: Select the remote control you wish to use.
      selector:
        entity:
          filter:
            domain: sensor

    target_light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          domain: light

trigger:
  - platform: state
    entity_id: !input 'remote'
    attribute: action

condition: []

action:
  - variables:
      command: " {{ trigger.to_state.attributes.action }} "
      var_light: !input target_light
      
  - choose:
      # Short press on UP
      - conditions:
          - condition: template
            value_template: "{{ command == \"on\" }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data: {}
                        
      # Short press on DOWN
      - conditions:
          - condition: template
            value_template: "{{ command == \"off\" }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
            data: {}
mode: single
